# Generated by Django 3.0.3 on 2020-02-06 04:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_Question',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
